<script lang="ts">
	import Example from '$lib/docs/Example.svelte';
	import MockIDE, { type IdeToken } from '$lib/components/MockIDE.svelte';

	const SAMPLE_TOKENS: IdeToken[] = [
		{ c: '// generated by synthetica · push to merge\n', cls: 'com' },
		{ c: 'export async function ', cls: 'key' },
		{ c: 'POST', cls: 'fn' },
		{ c: '(req: Request) {\n' },
		{ c: '  const ', cls: 'key' },
		{ c: '{ prompt, userId } ' },
		{ c: '= ', cls: 'key' },
		{ c: 'await req.' },
		{ c: 'json', cls: 'fn' },
		{ c: '();\n' },
		{ c: '  return ', cls: 'key' },
		{ c: 'stream', cls: 'fn' },
		{ c: '({ model: ' },
		{ c: '"claude-opus-4-7"', cls: 'str' },
		{ c: ', prompt });\n' },
		{ c: '}\n' }
	];
</script>

<Example
	title="Streaming TS handler"
	stretch
	code={`<MockIDE
  filename="~/synthetica/app/api/route.ts"
  tokens={[
    { c: "// generated by synthetica\\n", cls: "com" },
    { c: "export async function ", cls: "key" },
    { c: "POST", cls: "fn" },
    { c: "(req: Request) {\\n" },
    // …
  ]}
/>`}
>
	<div style="padding:24px">
		<MockIDE filename="~/synthetica/app/api/route.ts" tokens={SAMPLE_TOKENS} thinkingLabel="AI is writing…" />
	</div>
</Example>
