<script lang="ts">
	import { base } from '$app/paths';

	import StickyBanner from '$lib/components/StickyBanner.svelte';
	import Button from '$lib/components/Button.svelte';
	import Sparkle from '$lib/components/Sparkle.svelte';
	import EyebrowPill from '$lib/components/EyebrowPill.svelte';
	import GradientText from '$lib/components/GradientText.svelte';
	import Rotator from '$lib/components/Rotator.svelte';
	import Aurora from '$lib/components/Aurora.svelte';
	import NodeGraphBackground from '$lib/components/NodeGraphBackground.svelte';
	import FloatingSparkles from '$lib/components/FloatingSparkles.svelte';
	import PromptHero from '$lib/components/PromptHero.svelte';
	import StatCounter from '$lib/components/StatCounter.svelte';
	import LogoMarquee from '$lib/components/LogoMarquee.svelte';
	import LogoRow from '$lib/components/LogoRow.svelte';
	import AsciiHero from '$lib/components/AsciiHero.svelte';
	import MockIDE, { type IdeToken } from '$lib/components/MockIDE.svelte';
	import GlassCard from '$lib/components/GlassCard.svelte';
	import GlassCardIcon from '$lib/components/GlassCardIcon.svelte';
	import GlassCardTitle from '$lib/components/GlassCardTitle.svelte';
	import GlassCardBody from '$lib/components/GlassCardBody.svelte';
	import GlassCardLink from '$lib/components/GlassCardLink.svelte';
	import BeforeAfter from '$lib/components/BeforeAfter.svelte';
	import ChatBubble from '$lib/components/ChatBubble.svelte';
	import TokenStream from '$lib/components/TokenStream.svelte';
	import PricingCard, {
		PricingTier,
		PricingAmount,
		PricingBlurb,
		PricingFeatures,
		PricingFlag,
		PricingCTA
	} from '$lib/components/PricingCard.svelte';
	import WaitlistForm from '$lib/components/WaitlistForm.svelte';
	import CommunityBadge from '$lib/components/CommunityBadge.svelte';
	import ChatFAB from '$lib/components/ChatFAB.svelte';
	import ChatFABHeader from '$lib/components/ChatFABHeader.svelte';
	import ChatFABBody from '$lib/components/ChatFABBody.svelte';

	import './demo.css';

	const ic = (slug: string) => `https://cdn.jsdelivr.net/npm/simple-icons@11/icons/${slug}.svg`;

	const IDE_TOKENS: IdeToken[] = [
		{ c: '// generated by synthetica · push to merge\n', cls: 'com' },
		{ c: 'export async function ', cls: 'key' },
		{ c: 'POST', cls: 'fn' },
		{ c: '(req: Request) {\n' },
		{ c: '  const ', cls: 'key' },
		{ c: '{ prompt, userId } ' },
		{ c: '= ', cls: 'key' },
		{ c: 'await req.' },
		{ c: 'json', cls: 'fn' },
		{ c: '();\n' },
		{ c: '  return ', cls: 'key' },
		{ c: 'stream', cls: 'fn' },
		{ c: '({ model: ' },
		{ c: '"claude-opus-4-7"', cls: 'str' },
		{ c: ', prompt });\n' },
		{ c: '}\n' }
	];
</script>

<svelte:head>
	<title>Synthetica — AI for the next generation of work ✦</title>
	<meta
		name="description"
		content="A performative-ui-svelte showcase: every component assembled into one over-the-top AI startup landing page."
	/>
</svelte:head>

<div class="synthetica" data-theme="dark">
	<a class="syn-back-link" href={base || '/'}>← back to docs</a>

	<!-- 00 · Sticky pill -->
	<StickyBanner trailing={pillArrow}>Backed by Y Combinator (W26) — we just raised our seed</StickyBanner>
	{#snippet pillArrow()}<span aria-hidden="true">→</span>{/snippet}

	<!-- 01 · Nav -->
	<nav class="syn-nav">
		<a class="syn-brand" href="#top">
			<span class="syn-brand-mark">◣</span>
			<span>synthetica</span>
			<span class="syn-brand-tag">beta</span>
		</a>
		<div class="syn-nav-links">
			<a href="#product">Product</a>
			<a href="#pricing">Pricing</a>
			<a href="#docs">Docs</a>
			<a href="#blog">Blog</a>
			<a href="#customers">Customers</a>
		</div>
		<div class="syn-nav-cta">
			<a class="syn-nav-login" href="#">Log in</a>
			<Button as="a" href="#" variant="shimmer" size="sm" sparkle>Start building</Button>
		</div>
	</nav>

	<!-- 02 · Hero -->
	<header class="syn-hero" id="top">
		<div class="syn-hero__bg">
			<Aurora
				animated
				blobs={[
					{ color: 'rgba(124,58,237,0.55)', x: 30, y: 40, size: 55 },
					{ color: 'rgba(236,72,153,0.45)', x: 65, y: 35, size: 50 },
					{ color: 'rgba(6,182,212,0.40)', x: 55, y: 75, size: 50 },
					{ color: 'rgba(251,191,36,0.30)', x: 25, y: 70, size: 40 }
				]}
			/>
			<NodeGraphBackground density={55} />
			<FloatingSparkles count={22} />
		</div>

		<div class="syn-hero__inner">
			<EyebrowPill>Now with GPT-5.5 Turbo Vision Pro</EyebrowPill>

			<h1 class="syn-hero__headline">
				AI for
				<GradientText>
					<Rotator words={['everyone', 'doctors', 'lawyers', 'founders', 'the rest of us']} />
				</GradientText>
			</h1>

			<p class="syn-hero__sub">
				The end-to-end platform for teams who refuse to ship
				<GradientText>slop</GradientText>. Built on the frontier. Designed for
				<GradientText>velocity</GradientText>.
			</p>

			<div class="syn-hero__prompt">
				<PromptHero placeholder="Describe what you want to build…" ctaLabel="Generate" />
			</div>

			<div class="syn-hero__ctas">
				<Button as="a" href="#" variant="ghost">Talk to sales →</Button>
				<a class="syn-hero__secondary" href="#">
					<span class="syn-play" aria-hidden="true">▶</span>
					<span>Watch the 90-second demo</span>
				</a>
			</div>

			<div class="syn-powered">
				<span>Powered by</span>
				<img src={ic('openai')} alt="OpenAI" />
				<span>·</span>
				<img src={ic('anthropic')} alt="Anthropic" />
				<span>·</span>
				<img src={ic('googlegemini')} alt="Gemini" />
			</div>
		</div>

		<div class="syn-scroll-hint">
			<span>scroll</span>
			<span class="syn-scroll-arrow" aria-hidden="true">↓</span>
		</div>
	</header>

	<!-- 03 · Trust bar -->
	<section class="syn-trust" id="customers">
		<p class="syn-trust__headline">
			Trusted by
			<GradientText><StatCounter target={51842} /></GradientText>
			builders at the world's most ambitious teams
		</p>
		<LogoMarquee
			speed={30}
			logos={[
				{ kind: 'img', src: ic('openai'), alt: 'OpenAI' },
				{ kind: 'img', src: ic('stripe'), alt: 'Stripe' },
				{ kind: 'img', src: ic('anthropic'), alt: 'Anthropic' },
				{ kind: 'node', node: nasa },
				{ kind: 'img', src: ic('notion'), alt: 'Notion' },
				{ kind: 'img', src: ic('shopify'), alt: 'Shopify' },
				{ kind: 'node', node: harvard },
				{ kind: 'img', src: ic('vercel'), alt: 'Vercel' },
				{ kind: 'img', src: ic('github'), alt: 'GitHub' },
				{ kind: 'img', src: ic('nvidia'), alt: 'NVIDIA' }
			]}
		/>
	</section>
	{#snippet nasa()}<span class="pui-marquee__text">NASA</span>{/snippet}
	{#snippet harvard()}<span style="font-family:var(--pui-font-serif)">Harvard</span>{/snippet}

	<!-- 04 · Stat flex -->
	<section class="syn-statflex">
		<div class="syn-stat">
			<div class="syn-stat__num"><GradientText>10B+</GradientText></div>
			<div class="syn-stat__label">tokens processed daily</div>
		</div>
		<div class="syn-stat">
			<div class="syn-stat__num"><GradientText>99.99%</GradientText></div>
			<div class="syn-stat__label">uptime SLA</div>
		</div>
		<div class="syn-stat">
			<div class="syn-stat__num"><GradientText>&lt;200ms</GradientText></div>
			<div class="syn-stat__label">p50 latency, anywhere</div>
		</div>
		<div class="syn-stat">
			<div class="syn-stat__num"><GradientText>SOC 2</GradientText></div>
			<div class="syn-stat__label">Type II · HIPAA · GDPR</div>
		</div>
	</section>

	<!-- 05 · ASCII hero -->
	<section class="syn-section" style="text-align:center">
		<span class="syn-eyebrow"><span class="syn-dot"></span>The brutalist hero</span>
		<h2 class="syn-title centered">
			Built for the <GradientText>terminal-native</GradientText> generation
		</h2>
		<div style="margin-top:28px">
			<AsciiHero colorful />
		</div>
		<p class="syn-caption">move your cursor over it. yes, we know.</p>
	</section>

	<!-- 06 · Mock IDE -->
	<section class="syn-section" id="product">
		<span class="syn-eyebrow"><span class="syn-dot"></span>Watch AI ship for you</span>
		<h2 class="syn-title">Your <GradientText>copilot</GradientText>, but it actually merges</h2>
		<div style="margin-top:32px">
			<MockIDE
				filename="~/synthetica/app/api/route.ts"
				tokens={IDE_TOKENS}
				thinkingLabel="AI is writing…"
			/>
		</div>
	</section>

	<!-- 07 · Glass cards -->
	<section class="syn-section">
		<span class="syn-eyebrow"><span class="syn-dot"></span>The platform</span>
		<h2 class="syn-title">Three primitives. <GradientText>Infinite</GradientText> possibility.</h2>
		<div class="syn-cards">
			<GlassCard breathing>
				<GlassCardIcon>✦</GlassCardIcon>
				<GlassCardTitle>Reason</GlassCardTitle>
				<GlassCardBody>
					A frontier-class reasoning engine that thinks before it speaks. Multi-step. Multi-modal.
					Multi-vendor.
				</GlassCardBody>
				<GlassCardLink href="#">Learn more</GlassCardLink>
			</GlassCard>
			<GlassCard breathing>
				<GlassCardIcon>◇</GlassCardIcon>
				<GlassCardTitle>Retrieve</GlassCardTitle>
				<GlassCardBody>
					Bring your private knowledge to the model. Vector, hybrid, graph — we pick the right index
					for every query, every time.
				</GlassCardBody>
				<GlassCardLink href="#">Learn more</GlassCardLink>
			</GlassCard>
			<GlassCard breathing>
				<GlassCardIcon>◆</GlassCardIcon>
				<GlassCardTitle>Act</GlassCardTitle>
				<GlassCardBody>
					Agents that don't just respond. They schedule, draft, deploy, and refund. With audit logs
					your security team will actually like.
				</GlassCardBody>
				<GlassCardLink href="#">Learn more</GlassCardLink>
			</GlassCard>
		</div>
	</section>

	<!-- 08 · Stop / Start -->
	<section class="syn-stopstart">
		<h2>
			Stop
			<GradientText>
				<Rotator
					words={['context-switching', 'writing emails', 'shipping slop', 'tab-hoarding']}
					typeMs={55}
					holdMs={1100}
					hideCursor
				/>
			</GradientText>.
			<br />
			Start
			<GradientText>
				<Rotator
					words={['shipping', 'reasoning', 'compounding', 'winning']}
					typeMs={55}
					holdMs={1100}
					hideCursor
				/>
			</GradientText>.
		</h2>
	</section>

	<!-- 09 · Before / After -->
	<section class="syn-section">
		<span class="syn-eyebrow"><span class="syn-dot"></span>The transformation</span>
		<h2 class="syn-title">
			The old way is <span class="syn-strike">fine</span> <GradientText>broken</GradientText>.
		</h2>
		<div style="margin-top:32px">
			<BeforeAfter
				brand="Synthetica"
				before={[
					'14 tabs open',
					'3 hours of meetings about meetings',
					'A spreadsheet from 2019',
					'Vibes-based prioritization',
					'Slack at 11pm'
				]}
				after={[
					'One pane of glass',
					'Async by default',
					'Your data, working',
					'Outcome-driven',
					'Inbox zero, sustainably'
				]}
			/>
		</div>
	</section>

	<!-- 10 · Token stream -->
	<section class="syn-section">
		<span class="syn-eyebrow"><span class="syn-dot"></span>See it think</span>
		<h2 class="syn-title">Reasoning you can <GradientText>watch happen</GradientText>.</h2>
		<div style="margin-top:32px;display:flex;flex-direction:column;gap:14px;max-width:680px">
			<ChatBubble role="user">
				Summarize Q3 churn by cohort and tell me what's bleeding.
			</ChatBubble>
			<ChatBubble role="ai" agent="Synthetica" thinking="reasoning…">
				<TokenStream
					text="Q3 churn is bleeding from your SMB cohort. Net retention there is 71% vs. 104% in mid-market and 118% in enterprise. The fix: gate self-serve onboarding behind an activation milestone."
					loop
				/>
			</ChatBubble>
		</div>
	</section>

	<!-- 11 · Pricing -->
	<section class="syn-section" id="pricing">
		<span class="syn-eyebrow"><span class="syn-dot"></span>Pricing</span>
		<h2 class="syn-title">Simple, <GradientText>usage-based</GradientText> pricing.</h2>
		<div class="syn-prices">
			<PricingCard>
				<PricingTier>Hobby</PricingTier>
				<PricingAmount unit="/mo">$0</PricingAmount>
				<PricingBlurb>For weekend experiments.</PricingBlurb>
				<PricingFeatures>
					<li>10K tokens / day</li>
					<li>Community support</li>
					<li>1 project</li>
				</PricingFeatures>
				<PricingCTA href="#">Start free</PricingCTA>
			</PricingCard>
			<PricingCard featured>
				<PricingFlag>Most popular</PricingFlag>
				<PricingTier>Pro</PricingTier>
				<PricingAmount unit="/mo">$49</PricingAmount>
				<PricingBlurb>For the serious solo builder.</PricingBlurb>
				<PricingFeatures>
					<li>1M tokens / day</li>
					<li>Priority routing</li>
					<li>Unlimited projects</li>
					<li>Eval dashboard</li>
				</PricingFeatures>
				<PricingCTA href="#">Upgrade</PricingCTA>
			</PricingCard>
			<PricingCard>
				<PricingTier>Enterprise</PricingTier>
				<PricingAmount>Custom</PricingAmount>
				<PricingBlurb>For teams who say "leverage" a lot.</PricingBlurb>
				<PricingFeatures>
					<li>Volume credits</li>
					<li>SOC 2 / HIPAA</li>
					<li>VPC deploy</li>
					<li>Dedicated SE</li>
				</PricingFeatures>
				<PricingCTA href="#">Talk to sales</PricingCTA>
			</PricingCard>
		</div>
	</section>

	<!-- 12 · Press -->
	<section class="syn-press">
		<p class="syn-press__headline">As seen in</p>
		<div class="syn-press__logos">
			<span class="syn-press__logo serif">TechCrunch</span>
			<span class="syn-press__logo serif italic">The Information</span>
			<span class="syn-press__logo serif">Forbes</span>
			<span class="syn-press__logo bold">BLOOMBERG</span>
			<span class="syn-press__logo serif">The New York Times</span>
			<span class="syn-press__logo">WIRED</span>
		</div>
	</section>

	<!-- 13 · Backers -->
	<section class="syn-backers">
		<LogoRow
			heading="Backed by"
			logos={[
				{ kind: 'img', src: ic('ycombinator'), alt: 'YC' },
				{ kind: 'node', node: 'a16z' },
				{ kind: 'node', node: sequoia },
				{ kind: 'node', node: 'FOUNDERS FUND' },
				{ kind: 'node', node: 'SV ANGEL' },
				{ kind: 'node', node: angels }
			]}
		/>
		<LogoRow
			heading="From alumni of"
			logos={[
				{ kind: 'node', node: 'Stanford' },
				{ kind: 'node', node: 'MIT' },
				{ kind: 'node', node: 'Berkeley' },
				{ kind: 'node', node: 'OpenAI' },
				{ kind: 'node', node: 'DeepMind' },
				{ kind: 'node', node: 'Stripe' }
			]}
		/>
	</section>
	{#snippet sequoia()}<span style="font-family:var(--pui-font-serif);font-style:italic">Sequoia</span>{/snippet}
	{#snippet angels()}<span style="font-style:italic">…and 47 angels you've heard of</span>{/snippet}

	<!-- 14 · Waitlist -->
	<section class="syn-waitlist">
		<div class="syn-waitlist__bg">
			<Aurora />
		</div>
		<div class="syn-waitlist__inner">
			<h2 class="syn-title centered">
				Join <GradientText><StatCounter target={8247} /></GradientText> builders on the waitlist.
			</h2>
			<p class="syn-waitlist__sub">
				We're rolling out access weekly. The earlier you join, the earlier you get in.
			</p>
			<WaitlistForm
				placeholder="you@startup.ai"
				ctaLabel="Join the waitlist"
				footnote="✦ No credit card · ✦ Cancel anytime · ✦ Your data stays yours"
			/>
		</div>
	</section>

	<!-- 15 · Community -->
	<section class="syn-community" id="docs">
		<CommunityBadge href="#" icon={ic('github')} title="Star us on GitHub">
			{#snippet subtitle()}<strong>12,847</strong> stars · +184 this week{/snippet}
		</CommunityBadge>
		<CommunityBadge
			href="#"
			icon={ic('discord')}
			title="Join the Discord"
			subtitle="8,201 builders online now"
		/>
		<CommunityBadge
			href="#"
			icon={ic('x')}
			title="Follow on X"
			subtitle="build in public, always"
		/>
	</section>

	<!-- 16 · Footer -->
	<footer class="syn-footer" id="blog">
		<div class="syn-footer__top">
			<div class="syn-footer__brand">
				<a class="syn-brand" href="#top">
					<span class="syn-brand-mark">◣</span>
					<span>synthetica</span>
				</a>
				<p class="syn-footer__mission">
					We're building the AI platform we wish existed when we were shipping at the world's most
					ambitious teams.
				</p>
				<div class="syn-footer__soc2">
					<span class="syn-soc2">SOC 2 Type II</span>
					<span class="syn-soc2">HIPAA</span>
					<span class="syn-soc2">GDPR</span>
					<span class="syn-soc2">ISO 27001</span>
				</div>
			</div>
			<div class="syn-footer__cols">
				<div>
					<h4>Product</h4>
					<a href="#">Reason</a>
					<a href="#">Retrieve</a>
					<a href="#">Act</a>
					<a href="#">Eval</a>
					<a href="#">Changelog</a>
				</div>
				<div>
					<h4>Company</h4>
					<a href="#">About</a>
					<a href="#">Manifesto</a>
					<a href="#">Careers</a>
					<a href="#">Press kit</a>
				</div>
				<div>
					<h4>Resources</h4>
					<a href="#docs">Docs</a>
					<a href="#">API reference</a>
					<a href="#">Cookbook</a>
					<a href="#">Status</a>
				</div>
				<div>
					<h4>Legal</h4>
					<a href="#">Terms</a>
					<a href="#">Privacy</a>
					<a href="#">DPA</a>
					<a href="#">Subprocessors</a>
				</div>
			</div>
		</div>
		<div class="syn-footer__bottom">
			<span>© 2026 Synthetica Labs, Inc.</span>
			<span>Made with <Sparkle /> and questionable taste in San Francisco.</span>
		</div>
	</footer>

	<!-- 17 · Chat FAB -->
	<ChatFAB label="Ask AI">
		{#snippet popover()}
			<ChatFABHeader>Hi! I'm Synthi.</ChatFABHeader>
			<ChatFABBody>
				<p style="margin:0;color:var(--pui-fg-dim)">
					I'm an AI assistant trained on Synthetica's docs. What can I help you build today?
				</p>
			</ChatFABBody>
		{/snippet}
	</ChatFAB>
</div>
